### ISSUE TITLE
Universal Example

### ISSUE THREAD

**Issue by h18n** [anorudes/redux-easy-boilerplate#1]
Hi,

It will be great, if you can add universal JS execution to this boilerplate as well.

**Comment by anorudes** [comment]
Hello, harrybabu, i don't understand your problem, but in boilerplate was a bug after update and we fixed his. 
Also: This boilerplate is not for isomorphic application :)

**Comment by h18n** [comment]
Hi Anorudes,

I didnt had any issues with the boilerplate. I was giving a suggestion to make it isomorphic.
