### ISSUE TITLE
minetype -> mimetype in webpack.config.js

### ISSUE THREAD

**Issue by jsbUSMC** [anorudes/redux-easy-boilerplate#10]
I wanted to know, shouldn't the font loaders (woff, woff2, ttf, and svg) in webpack.config.js say mi**m**etype instead of mi**n**etype? I noticed that, and when I googled for _minetype_ it corrected to say "didn't you mean **_mime type**_." There was a similar issue that was brought up in Kriasoft's React Starter Kit as well that was corrected to mimetype. Thank you.

**Comment by anorudes** [comment]
jsbUSMC, thanks! I'll fix this soon)
