### ISSUE TITLE
Are there any plans for further documentation?

### ISSUE THREAD

**Issue by kbecker43** [anorudes/redux-easy-boilerplate#13]
Thanks for putting up this awesome project! I'm just learning the ins and outs of Webpack and React and this boilerplate has the exact tools I am looking for to get started. I'd love to be able to understand what the various pieces are doing, how it all works together, why some of the tools/patterns were chosen, how someone might go about customizing this to build out their own project, etc. Are there any plans to build out more detailed documentation or tutorials? Thanks again!

**Comment by thecodingwhale** [comment]
this would be a great idea!

**Comment by nickeblewis** [comment]
I think that would be useful - I have been exploring some of the more complex boilerplates out there such as the Universal/Isomorphic ones and this strips things down to purer react and redux, which is welcome by my book. So you can kind of learn from them and work it out here..... but that said, some more docs would be lovely :-)

**Comment by keske** [comment]
Thanks mates. I'll try to do a small but useful docs, asap.
