### ISSUE TITLE
Reason for the hash in the URL?

### ISSUE THREAD

**Issue by captDaylight** [anorudes/redux-easy-boilerplate#22]
Hey, love the project, but was wondering why you chose to have URL scheme like http://localhost:3000/#/list as opposed to http://localhost:3000/list.

It's a pretty simple change, but I was wondering if you had any thoughts around it.

_Anybody wanting to make the change, go to index.js and change the line_ 

```
import createHistory from 'history/lib/createHashHistory';
```

to

```
import { createHistory } from 'history';
```

**Comment by anorudes** [comment]
Becouse this boilerplate not have server-side rendering with express :( We will fix it in future)
