### ISSUE TITLE
doesn't work after build

### ISSUE THREAD

**Issue by anorudes** [anorudes/redux-easy-boilerplate#30]
The site doesn't work after build "npm run build" for unknown reasons yet )
The problem appear after last updates

**Comment by oltsa** [comment]
It worked locally - checking again

2016-01-05 17:03 GMT+02:00 anorudes notifications@github.com:

**Comment by anorudes** [comment]
Yes, local working very fine, but after build - white blank page and 0 errors

**Comment by anorudes** [comment]
You can check with the gh-pages branch :)

**Comment by oltsa** [comment]
You can revert back to before the webpack split, I have it saved in my fork
- i'll check it tonight

2016-01-05 17:07 GMT+02:00 anorudes notifications@github.com:

**Comment by anorudes** [comment]
Ye, i tried revert webpack split, but problem not resolved. Mystic

**Comment by anorudes** [comment]
I returned hashHistory because gh-pages have subdirectory. Now build version can work in any folders. We can make option in webpack for future :)

**Comment by anorudes** [comment]
+ I add commit 61bd5d1 because don't know why not working hashistory with webpack split)

**Comment by oltsa** [comment]
oooh where are you serving it? if you use historyPush api you need for e.g
.htaccess to server index.html in every case and let react-router handle
the rest

2016-01-05 18:05 GMT+02:00 anorudes notifications@github.com:

**Comment by anorudes** [comment]
I add commit decc73c because don't know why not working hashistory with webpack split)

**Comment by anorudes** [comment]
yes, i know this. The hashhistory added for simple build site in directory and upload in gh-pages.
url for demo: anorudes.github.io/redux-easy-boilerplate/ 
"redux-easy-boilerplate" subdirectory. It's not working without hashhistory

**Comment by oltsa** [comment]
I'll make the adjustments and return the hashHistory there (anyways if
someone wants to do it later, we can add to docs something about it)

2016-01-05 18:26 GMT+02:00 anorudes notifications@github.com:

**Comment by oltsa** [comment]
to my fork, or we could create a new branch for the updates

2016-01-05 18:30 GMT+02:00 Ollipekka Jalonen ollipekka.jalonen@gmail.com:

**Comment by oltsa** [comment]
I created http://anorudes.slack.com haven't used it much so I don't know if I have to invite you by e-mail

**Comment by anorudes** [comment]
I will make email in github settings public and you can send invite
