### ISSUE TITLE
What do you think about using react-bootstrap?

### ISSUE THREAD

**Issue by aleksUIX** [anorudes/redux-easy-boilerplate#39]
Is there any reason you might not want to integrate this into your boilerplate?

I am using this boilerplate for my portfolio website now - it is really cool. Would you like me to commit a version where bootstrap is replaced with react-bootstrap?

**Comment by oltsa** [comment]
In my opinion it shouldn't be added to this boilerplate, this should be just a simple starting point. 
Altho there is a bootstrap included in the boilerplate, it's not exactly the main point. Upto @anorudes.

If you wish to make a pull request, please do it against development branch

**Comment by donpinkus** [comment]
+1 for not including it. This is just react + redux boilerplate. 

Don't become react-redux-universal because you assembled everything, at which point we'll need to create another minimal boilerplate :P
