### ISSUE TITLE
Eslint errors with jsx-control-statements

### ISSUE THREAD

**Issue by stefaneng** [anorudes/redux-easy-boilerplate#4]
I was fixing some issues I had when using this boilerplate, and came across the issue of using `jsx-control-statements` with eslint.

```
$ npm run lint
...
  39:21  error  "index" is not defined  no-undef
  39:29  error  "item" is not defined   no-undef
  39:41  error  "item" is not defined   no-undef

✖ 3 problems (3 errors, 0 warnings)
```

More info on this thread:
https://github.com/valtech-au/jsx-control-statements/issues/7

Just wanted to put the issue up here in case anyone ran into the same problem.

**Comment by anorudes** [comment]
Maybe need to delete jsx-control-statements from the boilerplate. What do you think?

**Comment by stefaneng** [comment]
Check out the commit I added and let me know if that looks like a decent replacement.
I personally took `jsx-control-statements` out, and it seems like anyone that wants to add it back it could do so.
