### ISSUE TITLE
Should hot loading work for reducers?

### ISSUE THREAD

**Issue by bebraw** [anorudes/redux-easy-boilerplate#40]
When trying to perform a trivial change to a reducer, I got the following:

![screenshot 2016-01-09 15 24 07](https://cloud.githubusercontent.com/assets/166921/12216292/194dea6c-b6e5-11e5-8f9c-eb83f4fe8951.png)

Is hot loading supported for reducers in your boilerplate? It's broken in my personal setup as well (webpack-dev-server) and I'm trying to understand why both fail.

**Comment by oltsa** [comment]
http://stackoverflow.com/questions/34243684/make-redux-reducers-and-other-non-components-hot-loadable

this might probably relates to it and we have to fix this aswell

**Comment by bebraw** [comment]
@inertum Works great. Thanks.

**Comment by anorudes** [comment]
very nice!

**Comment by oltsa** [comment]
this is fixed in our package aswell
