### ISSUE TITLE
Server-side rendering?

### ISSUE THREAD

**Issue by amcsi** [anorudes/redux-easy-boilerplate#41]
It would be really cool if you'd support server-side rendering. Will there be support for it?

Although in that case you would need to move from hashHistory to use browserHistory

**Comment by oltsa** [comment]
It's in the TODOs 

If you'd like to help please make all PRs against the dev branch (#35)

**Comment by amcsi** [comment]
I would love to, but actually one of the reasons I opened this issue was that I didn't know how to do this combined with react-router (that uses browser history), so I was hoping that this project would tell me :D

**Comment by inertum** [comment]
https://github.com/rackt/example-react-router-server-rendering-lazy-routes/
