### ISSUE TITLE
Inaccurate Readme?

### ISSUE THREAD

**Issue by SKrauth** [anorudes/redux-easy-boilerplate#47]
I'm having trouble with with this error "Warning: The state (2nd) argument to history.createLocation is deprecated; use a location descriptor instead." If I understand the Readme correctly this is a result of the way `src/index.js` is set up. The Readme says I need to change `hashHistory` to `browserHistory` but neither of those exist in the current version of `src/index.js`, instead I find `useRouterHistory`.

Am I misunderstanding the Readme? What would be the correct update to this? Also, thanks for building this, I've just started taking my first steps into React.js and this has helped me so much.

**Comment by oltsa** [comment]
I think that part got factored out in some commit - have to fix that! 
that error message is coming with History (i think above 1.14.0). 
The new react-router doesn't really require it specially if you are serving it from web server using browserHistory, but still need to use it with hashHistory if you want to disable the hash key generation (as far as I've figured)
