### ISSUE TITLE
Deploying to Heroku error - "babel-core/register not found"

### ISSUE THREAD

**Issue by donpinkus** [anorudes/redux-easy-boilerplate#49]
Hey - this is an awesome boilerplate, good job keeping it minimal. 

I'm trying to deploy to Heroku, and I get this error `Error: Cannot find module 'babel-core/register'`.

The only place this seems to be used is bin/server.js. 

Thoughts?

**Comment by oltsa** [comment]
`blame`;) I have been really busy with work past week and haven't had chance to go through all the pull requests + our history had a slight hiccup :) I remember there was some update to the server so it might cause that. I personally haven't used heroku but I really doubt that for deployment you would use server.js as it's only used to pipe through webpack dev server and hot reloading.

I have on local new webpack/server configurations that I will push hopefully during this weekend

**Comment by jcperez-ch** [comment]
@donpinkus, not sure if that can help but heroku doesn't read packages from devDependencies on certain npm scripts (even I need to understand more about it) but you can always try to move babel-core to `dependencies` instead... I hope it works

**Comment by anorudes** [comment]
Hello, today the boilerplate was updated for 3 version
