### ISSUE TITLE
Production build: clearing browser cache

### ISSUE THREAD

**Issue by brandonwoo** [anorudes/redux-easy-boilerplate#68]
script and styles bundle are imported in `index.html` as follows:

```
<script src="dist/bundle.js"></script>
```

```
<link rel="stylesheet" type="text/css" href="dist/bundle.css"></style>
```

However in production builds, old scripts and styles will be loaded from browser cache since the import urls are static.

Would like to ask what is the recommended way to solve this problem?

**Comment by oltsa** [comment]
Without serverside injection of the script might be trickier, but I think
the commonly used is bundle.js?v=_some hash_ that changes everytime there
is changes to the file

2016-03-09 5:23 GMT+02:00 Brandon Woo notifications@github.com:

**Comment by vnglst** [comment]
Maybe letting Webpack add hashes to the Javascript files? I found this tutorial to be very helpful, see "Adding hashes to filenames": http://survivejs.com/webpack_react/building_kanban/#adding-hashes-to-filenames

**Comment by anorudes** [comment]
Hello, today the boilerplate was updated for 3 version and we have auto rimraf dist folder now
