### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ssmlee04** [anorudes/redux-easy-boilerplate#69]
I was making requests to my API server at `http://localhost:2999` but when I try to `GET` /something the error message is
`XMLHttpRequest cannot load http://localhost:2999/currencies. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`
I was wondering how to solve this issue? I tried to put 
`headers: { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Credentials": "true" },` in webpack-dev-middleware settings but it still won't work..

**Comment by oltsa** [comment]
Configure your api headers - look for info exactly with that
Access-Control-Allow-Origin , cors stuff have it's own kinks

2016-03-18 5:23 GMT+02:00 Shih-Min Lee notifications@github.com:

**Comment by oltsa** [comment]
Also localhost effects cors - i have in hosts file dev.localhost routed to
localhost

**Comment by anorudes** [comment]
Hello, today the boilerplate was updated for 3 version
