### ISSUE TITLE
remove react-hot-loader from devdependency?

### ISSUE THREAD

**Issue by AllenFang** [anorudes/redux-easy-boilerplate#72]
Hi @anorudes, it's a nice repo for redux starter. However, I found the `react-hot-loader` still remain in [dev dependency](https://github.com/anorudes/redux-easy-boilerplate/blob/master/package.json#L82). But according to the #54, it has moved to react transform and babel HMR, so just a question for any consideration for using `react-hot-loader`?

**Comment by anorudes** [comment]
Hello, today the boilerplate was updated for 3 version

**Comment by AllenFang** [comment]
That's awesome.
