### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by rokotyan** [anorudes/redux-easy-boilerplate#77]
`npm install` fails with the following error message:

```
npm ERR! peerinvalid The package react@15.0.0-rc.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-router@2.4.0 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-dom@15.0.0-rc.2 wants react@^15.0.0-rc.2
npm ERR! peerinvalid Peer react-addons-perf@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-css-transition-group@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8
npm ERR! peerinvalid Peer react-notification-system@0.2.7 wants react@0.14.x || ^15.0.0
npm ERR! peerinvalid Peer enzyme@2.3.0 wants react@0.13.x || 0.14.x || ^15.0.0-0
npm ERR! peerinvalid Peer pure-render-decorator@0.2.0 wants react@^0.14.0
```

**Comment by anorudes** [comment]
Hello, @Rokotyan Can you tell me your version node, npm?
"npm start" doesn't work after install?

**Comment by rokotyan** [comment]
Thank for a quick response @anorudes. Below are the versions of the global installs:
node 4.2.4
npm 2.14.12
webpack 1.13.0

`npm start` fails with: `sh: rimraf: command not found`

I'm on the latest version of OS X.

**Comment by anorudes** [comment]
try "npm install rimraf -g"

**Comment by rokotyan** [comment]
Getting more errors:

```
/Users/nikitarokotyan/Downloads/redux-easy-boilerplate-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:220
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/Users/nikitarokotyan/Downloads/redux-easy-boilerplate-master/.babelrc" at 1, attempted to resolve relative to "/Users/nikitarokotyan/Downloads/redux-easy-boilerplate-master"
```

Let me know if there is a way for me to help solving the issue.

**Comment by anorudes** [comment]
@Rokotyan Can you update npm to 3 version, node to 5 and global webpack to 2 (not sure what need)? :)

**Comment by oltsa** [comment]
Its dep depency, not compatible with 15. As it is

**Comment by anorudes** [comment]
I tested: after "rm -rf node_modules" and "npm install" - the boilerplate working. Most likely the problem with version node or npm

**Comment by anorudes** [comment]
@Rokotyan add me in skype - void-anoru, we both from Russia =)

**Comment by oltsa** [comment]
Ill add you too :)

**Comment by rokotyan** [comment]
Ok, it looks like newer versions of `npm` don't care about unmet dependencies and just keep installing things. Installing `node` 5.0 via `nvm` did the job. It would be nice if you could add it to the readme to avoid further confusion.

Terminal command I've used:

```
nvm install 5.0
nvm use 5.0
```

**Comment by anorudes** [comment]
I'm glad that it's working now :)
