### ISSUE TITLE
HotReloading pure function components.

### ISSUE THREAD

**Issue by michael-donat** [anorudes/redux-easy-boilerplate#80]
This is not an issue report but a question I couldn't find an answer for on my own.

As we were evaluating a number of bootstrap projects, what we've noticed about this one is that it hot reloads pure function components using react-transform + react-transform-hmr - something that should not be possible according to many sources (especially the author of above tool).

Would you mind shedding some light on how was this achieved?

**Comment by anorudes** [comment]
Hello, @michael-donat. Yee, pure function hot reload is working, but i had problems with him in old version of the boilerplate
If you will use this boilerplate please tell me when meet this problem again.
