### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by mgeduld** [anorudes/redux-easy-boilerplate#83]
Hi. I get a blank screen in the browser and this error in terminal: 

ERROR in ./~/react-addons-perf/index.js
Module not found: Error: Can't resolve 'react/lib/ReactDefaultPerf' 

node v5.2.0
npm 3.5.2

I went through the installation instructions and did an npm install.

**Comment by mgeduld** [comment]
I just updated to the latest node and npm, and I tried npm install react-default-perf. Now I'm no longer getting the error, but I still see a blank page in the browser. In console, I get these errors: 

vendor.js:2 Uncaught SyntaxError: Unexpected token <  (in vender.js:2)
main.js:2 Uncaught SyntaxError: Unexpected token < (in main.js:2)

**Comment by mgeduld** [comment]
I was wrong. I am still getting the Can't resolve 'react/lib/ReactDefaultPerf' error.

**Comment by mgeduld** [comment]
Upgrading to react 15.0.2 fixes the problem. I'll submit a PR later today.

**Comment by mgeduld** [comment]
Er ... I guess that's a downgrade, not an upgrade. Since the current version is 15.1.0. So ... problem not solved--at least not in a good way.

**Comment by anorudes** [comment]
Thanks for reporting! I will fix this errory today
