### ISSUE TITLE
Fresh install fails [webpack]

### ISSUE THREAD

**Issue by maxgram** [anorudes/redux-easy-boilerplate#85]
Hey guys,
First of all - awesome boilerplate! Thanks for putting it all together!

I tried to do fresh install and it fails on `npm run start` because of webpack lib Chunk:

```
Server is listening on http://:::3000
/redux-easy-boilerplate/node_modules/webpack/lib/Chunk.js:34
throw new Error("Chunk.entry was removed. Use hasRuntime()");
```

Works like a charm with "webpack": "^2.0.7-beta" and breaks right on "2.1.0-beta.0"

It seems like solution might be to update extract-text-webpack-plugin@^2.0.0-beta [here](https://github.com/webpack/extract-text-webpack-plugin/issues/210) but that lib also has breaking changes

here is a pull request to fix the bug https://github.com/anorudes/redux-easy-boilerplate/pull/84

**Comment by anorudes** [comment]
Thanks @max-gram, i just forgot about pull request)

**Comment by maxgram** [comment]
@anorudes I also noticed "react-router" has to be updated to 2.6.1 as well. However, if I update react-router under "dependencies" in the browser it results as error:

> Uncaught Invariant Violation: You have provided a history object created with history v3.x. This version of React Router is not compatible with v3 history objects. Please use history v2.x instead.

If I move it under devDependencies and reinstall all node_modules it works. The reason is well described [here](http://stackoverflow.com/a/22004559). I'm not sure if you want to make this change, but if you do, I can make pull request. Would you like me to do so?

**Comment by anorudes** [comment]
@max-gram Thanks, i updated the boilerplate today.

https://github.com/anorudes/redux-easy-boilerplate/commit/9875b702500e63e4ddd4a8557ca7b387d35a8679

Yes, you can help anytime with pullrequest =)
